on:
  issues:
    types: [opened]

jobs:
  issue_creator_job:
    runs-on: ubuntu-latest
    name: Issue card handler
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Issue Card Creator
        uses: somnolentPumpkin/issue-card-creator@Action
        id: hello
        with:
          actions: '{"data": [
            {
              "label": "test",
              "project": "Project 2",
              "project_type": "org",
              "column": "Column 2",
              "org": "qe-test-org"
            },{
            }
          ]}'
